config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # Sidekiq Web UI
  authenticate :user, lambda { |u| u.is_admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

  # Root
  root 'welcome#index'

  # Devise
  devise_for :users , controllers: {
    registrations: 'users/registrations'
  }

  # Resource
  resources :posts
  resources :topics, except: [:destroy]
  resources :messages
  resources :starred_topics, only: [:index, :destroy, :create]

  # Search
  post "search" => "search#search"

end

app/views/shared/_chatbox.html.erb
<% messages = @chattable.messages.order("id DESC").first(100) %>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-success panel-main">
      <div class="panel-heading">
        Chatbox
      </div>
      <div class="panel-body">
        <%= form_for @new_message, remote: true, html: { id: 'chatroom-send-form' } do |f| %>
        <%= f.hidden_field :chattable_type %>
        <%= f.hidden_field :chattable_id %>
        <div class="row">
          <div class="col-md-8">
            <div class="form-group">
              <%= f.text_field :content, class: 'form-control', id: 'input-content' %>
            </div>
          </div>
          <div class="col-md-2">
            <%= f.submit t(:send), class: 'btn btn-default' %>
          </div>
        </div>
        <% end %>
      </div>
      <div class="panel-body" id="chatroom-content">
        <% messages.each do |msg| %>
        <%= render partial: 'shared/chatitem', locals: { msg: msg } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_chatitem.html.erb
<p class="text-primary">
  <small class="text-muted">
    <%= msg.user.nickname %> (#<%= msg.user.id %>)
    <span class="pull-right"><%= time_ago_in_words msg.created_at %></span>
  </small>
  <br/>
  <%= msg.content %>
</p>

app/views/shared/_footer.html.erb
<div class="container-fluid">
  <div class="row text-center">
    <p>
      <small>Copyright 2015 IslandZero</small>&nbsp;<small><a href="mailto:hi@yanke.io">hi@yanke.io</a></small>
      <br/>
      <small>Powered By <%= link_to 'Ruby on Rails', 'http://rubyonrails.org' %> | Themed By <%= link_to 'Bootswatch', 'http://bootswatch.com' %></small>
      <br/>
      <small>Links: <%= link_to "Github Repo", 'https://github.com/yanke-guo/IslandZero.git' %> | <%= link_to "YANKE.IO", 'http://yanke.io' %> | <%= link_to 'Donate', 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=KTR8BN7CF9CZ4' %></small>
    </p>
    <br/>
  </div>
</div>

app/views/shared/_ga.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', '<%= ENV['GA_TRACK_ID'] %>', 'auto');
ga('send', 'pageview');

</script>
<% end %>

app/views/shared/_ga_head.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');

ga('create', '<%= ENV['GA_TRACK_ID'] %>', 'auto');

</script>
<% end %>

app/views/shared/_ga_page_view.html.erb
<% if ENV['GA_TRACK_ID'].present? %>
<script>ga('send', 'pageview');</script>
<% end %>

app/views/shared/_nav.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:islandzero), topics_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav navbar-left">
        <%= li_link t('all_topics'), topics_path %>
      </ul>
      <%= form_tag search_path, class: "navbar-form navbar-left", role: "search" do %>
      <div class="form-group">
        <%= text_field_tag :keyword, params[:keyword], class: 'form-control', placeholder: t(:search_topic) %>
      </div>
      <button type="submit" class="btn btn-info"><%= glyphicon :search %></button>
      <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.nickname %><b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to t(:profile), edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to t(:logout), destroy_user_session_path, { method: :delete } %></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= li_link t('starred_topics'), starred_topics_path %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_nav_not_logined.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to t(:islandzero), root_path, class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= li_link t('login'), new_user_session_path %>
        <%= li_link t('register'), new_user_registration_path %>
      </ul>
    </div>
  </div>
</div>